### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jeenalee** [jeenalee/ColorsOfThrones#1]
1. Decide on which Houses/Groups to represent.
- Lannister (crimson / gold)
- Greyjoy (grey-blue / yellow squid)
- Stark (white / grey)
- Targeryan (red / black)
- Arryn (white / skyblue; "white moon and falcon")
- Martell (deserty; "red sun pierced by golden sun")
- Tyrell (green field / red rose)
- Baratheon (black / yellow)
- Tully (silver-trout / steely blue-darker river / red-salmon)
- White Walkers (blue to white)
- Children of the Forest (green to yellow to brown)

2. Come up with the color palette for each one of them (like 8 colors?).
- [ ] Lannister (750803, F7AF00, FFE17B, 5C023F, 414042)
- [ ] Greyjoy
- [ ] Stark
- [ ] Targeryan
- [ ] Arryn
- [ ] Martell
- [ ] Tyrell
- [ ] Baratheon
- [ ] Tully
- [ ] White Walkers (blue to white)
- [ ] Children of the Forest (green to yellow to brown)

3. Make sample graphs (hopefully with data about each House) for each color scheme.
- [ ] Lannister
- [ ] Greyjoy
- [ ] Stark
- [ ] Targeryan
- [ ] Arryn
- [ ] Martell
- [ ] Tyrell
- [ ] Baratheon
- [ ] Tully
- [ ] White Walkers (blue to white)
- [ ] Children of the Forest (green to yellow to brown)

4. Make a RMarkdown HTML page for gh-page.

5. Register for CRAN.
